
[window]
#decorations="None"
opacity=0.9
dimensions= {columns=120, lines =40}

[font]
	normal={family="Terminess Nerd Font Mono", style="Regular"}
	bold={style="Bold"}
	italic={style="Italic"}
	size=12

[cursor]
	style={shape="Underline", blinking="Off"}

[general]
import = [
	#"~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
  "~/.config/alacritty/themes/themes/iris.toml"
]
